version: '2'

services:

  mariadb:
    image: 'mariadb'
    volumes:
      - '/srv/docker/ghost/mariadb/:/var/lib/mysql'
    env_file:
      - back-tier.env
    networks:
      - back-tier

  web:
    build: .
    command: ["npm", "start"]
    ports:
      - '80:2368'
    volumes:
      - '/srv/docker/ghost/web/:/var/lib/ghost'
      - './config.js:/var/lib/ghost/config.js'
    links:
      - mariadb
    env_file:
      - ghost.env
      - back-tier.env
    networks:
      - back-tier

networks:
  back-tier:
    driver: bridge
